---
# root work
- block:
    - name: Add go repo (http://go-repo.io/) for CentOS
      yum_repository:
        name: go-repo
        description: go-repo.io
        gpgkey: https://mirror.go-repo.io/centos/RPM-GPG-KEY-GO-REPO
        baseurl: https://mirror.go-repo.io/centos/$releasever/$basearch/
      when:
        ansible_distribution == "CentOS"

    - name: Add go repo (http://go-repo.io/) for Fedora
      yum_repository:
        name: go-repo
        description: go-repo.io
        gpgkey: https://mirror.go-repo.io/fedora/RPM-GPG-KEY-GO-REPO
        baseurl: https://mirror.go-repo.io/fedora/$releasever/$basearch/
      when:
        ansible_distribution == "Fedora"

    - name: Install golang
      package:
        name: golang
        state: present
  become: true
  become_user: root

# user work
- name: Setup GOPATH directory structure
  file:
    path: "{{ ansible_env.HOME }}/{{gopath}}"
    state: directory

- name: Setup GOPATH environment variable
  lineinfile:
    path: "{{ ansible_env.HOME}}/.bash_profile"
    line: "export GOPATH=$HOME/{{ gopath }}"
